[package]
name = "proxmox-resource-scheduling"
version = "0.2.1"
authors = [
    "Fiona Ebner <f.ebner@proxmox.com>",
    "Proxmox Support Team <support@proxmox.com>",
]
edition = "2021"
license = "AGPL-3"
description = "Proxmox library for resource scheduling"
homepage = "https://www.proxmox.com"

exclude = [ "debian" ]

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
